---
- name: Hello AAP
  hosts: all
  gather_facts: true 
  #hosts: '*.home.lab'
  tasks:

    - name: Limit fact gathering
      ansible.builtin.setup:
        gather_subset:
          - hardware
      when: ansible_os_family == "RedHat"
          
    - name: Print all facts
      ansible.builtin.debug:
        var: ansible_facts
        
    - name: Say Hi
      ansible.builtin.debug:
        msg: "Hi!"
      when: ansible_facts["os_family"] == "RedHat"
