---
- name: Hello AAP
  hosts: all
  gather_facts: true 
  #hosts: '*.home.lab'
  tasks:
    - name: Say Hi
      ansible.builtin.debug:
        msg: "Hi!"
      when: ansible_facts["os_name"] == "RedHat"
