---
- name: Webhook listener
  hosts: localhost
  gather_facts: true

  sources:

    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 8080

    - name: Range
      ansible.eda.range:
        limit: 5

  rules:

    - name: Trigger a Playbook
      condition: event.payload is defined
      action:
        run_playbook:
          name: playbook.yml

    - name: React to 1
      condition: event.i == 1
      action:
        debug:
          msg: "Received counter event {{ event.i }}"

    - name: Multiple conditions, Multiple actions
      condition:
        all:
          - event.i == 2
          - fact.ansible_os_family == "Linux"
          - fact.ansible_distribution == "Red Hat Enterprise Linux"
      action:
        - print_event:
            pretty: true
        - run_playbook:
            name: playbook.yml
...
